apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: 
    $text: 'https://gist.github.com/unhurried/65be039436581b6a6124a5c53b890c43'
